title: Maverick Kaung
baseurl: 'https://www.mavjs.org/'
theme: mavjs

## Language
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

# Advanced
enableGitInfo: true
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
disableAliases: true
outputs:
  home:
    - HTML
    - RSS
  section:
    - HTML
    - RSS
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: title
      weight: 60
    - name: summary
      weight: 50
    - name: tags
      weight: 80
    - name: categories
      weight: 70
    - name: authors
      weight: 20
markup:
  highlight:
    style: dracula
    noClasses: true
    lineNos: false
  goldmark:
    renderer:
      unsafe: true
