[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[main]]
  name = "Photos"
  url = "https://photos.mavjs.org"
  weight = 4

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 6

[[main]]
  name = "Disclaimer"
  url = "#disclaimer"
  weight = 7

