# Site identity
description: "IT Security Enthusiast"
author: "Maverick Kaung"
twitter: mavjs

# Primary author slug (matches content/authors/<slug>/)
primary_author: admin

# Footer copyright — {year} is replaced at build time
copyright: '© {year} Ye Myat "Maverick" Kaung.'

# Contact section
contact:
  email: mavjs01+blog@gmail.com
  links:
    - icon: twitter
      icon_pack: fab
      name: mavjs @ twitter
      url: https://twitter.com/@mavjs
    - icon: mastodon
      icon_pack: fab
      name: mavjs @ infosec.exchange
      url: https://infosec.exchange/@mavjs
    - icon: keybase
      icon_pack: fab
      name: mavjs @ keybase
      url: https://keybase.io/mavjs

# Disclaimer section
disclaimer: "The opinions expressed on this site are mine alone and do not necessarily reflect the opinions or strategies of my past, present and future employers."
