# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: dark
  theme_night: dark
  font: dark
  font_size: M

# SEO

marketing:
  seo:
    site_type: Person
    twitter: 'mavjs'

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: "© {year} Ye Myat \"Maverick\" Kaung.<br />This work is licensed under {license}"
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Mon, Jan 2, 2006'
  time_format: '15:04'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    extra_languages:
      - python
      - yaml
      - go
      - rust
# Extensions

extensions:
  academicons:
    enable: true
